#!/usr/bin/env bash

cat << EOF > /oas/oas_install/biconfig.rsp
[ENGINE]
Response File Version=1.0.0.0.0
[GENERIC]
PERFORM_BI_STARTUP=true
SERVICE_INSTANCE_LIMIT=2
LOGOUT_URL=
CONFIGURE_BIEE=true
CONFIGURE_BIP=true
CONFIGURE_ESSBASE=false
INSTALL_EXALYTICS_IN_MEMORY_SOFTWARE=false
SERVICE_INSTANCE_MODE=SINGLE
DOMAIN_NAME=bi
DOMAINS_DIR=/oas/oas_install/Oracle/Middleware/Oracle_Home/user_projects/domains
ADMIN_USER_NAME=$1
ADMIN_PASSWORD=$2
ADMIN_CONFIRM_PASSWORD=$2
DOMAIN_WORK=LOCAL
SCHEMA_TYPE=SCHEMA_TYPE_NEW
DATABASE_TYPE=ORACLE
EXISTING_DATABASE_TYPE=ORACLE
CONNECT_STRING=$3
FAN_CONNECT_STRING=
NEW_DB_ADMIN_USERNAME=$4
NEW_DB_PASSWORD=$5
NEW_DB_SCHEMA_PREFIX=$6
NEW_DB_SCHEMA_PASSWORD=$7
NEW_DB_CONFIRM_SCHEMA_PASSWORD=$7
EXISTING_DB_PREFIX=
EXISTING_DB_PASSWORD=
EXISTING_DB_PREFIX=
EXISTING_DB_PASSWORD=
PORT_RANGE_START=9500
PORT_RANGE_END=9999
STATIC_PORTS_FILE=
APPLICATION_TYPE=APPLICATION_TYPE_EMPTY
BI_BUNDLE_FILE=
BI_BUNDLE_PASSWORD=<SECURE VALUE>
BI_APP_LITE_PASSWORD=<SECURE VALUE>
BI_DEFAULT_SERVICE_INSTANCE_KEY=bootstrap
EOF

if [[ $? -ne 0 ]]; then
    echo "Failed to Create config response file. Exiting..."
fi

